const FIXTURES = {
  squarePng: "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAGUlEQVQokWM4UZFCEmIY1VAxGkonhmvSAACsvaQQs35lUQAAAABJRU5ErkJggg==",
  rectangularPng: "iVBORw0KGgoAAAANSUhEUgAAABAAAAAYCAIAAAB8wupbAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAIElEQVQ4jWM4UZFCEmIY1VAxGkonRpNGymh+OEG7UgMA92F2H/KBCeEAAAAASUVORK5CYII=",
  oversizedPng: "iVBORw0KGgoAAAANSUhEUgAAEAEAAAAICAIAAAAZjsbdAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAB6ElEQVR4nO3dwQ0AIAgDQKv77+wK/mrIJR3AHDwFVvYRAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAIN9/sF/1FwgBAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECAQMwCagAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIZMr+encA+jUQAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECAQMwCagAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIZMr2dncA+jUQAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECAQMwCagAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIZMr2dncA+jUQAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECBAgAABAgQIECDwInABSfoAXsUTKhoAAAAASUVORK5CYII=",
  jpeg: "/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAQABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJYB8K//2Q==",
  webp: "UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoQABAAAUAmJaACdLoAA5gA/t7WP4tpHQpkP/maPvN9lvQ4AAA=",
};

function decode(name) {
  return Buffer.from(FIXTURES[name], "base64");
}

function png() {
  return decode("squarePng");
}

function rectangularPng() {
  return decode("rectangularPng");
}

function oversizedPng() {
  return decode("oversizedPng");
}

function jpeg() {
  return decode("jpeg");
}

function webp() {
  return decode("webp");
}

module.exports = { png, rectangularPng, oversizedPng, jpeg, webp };
